In [11]:
import numpy as np
import matplotlib.pylab
from numpy import random

In [47]:
a = np.array([1,2,3])
b = np.array((1,2,3))

In [48]:
a

array([1, 2, 3])

In [49]:
b

array([1, 2, 3])

In [50]:
a.dtype

dtype('int32')

In [51]:
b.dtype

dtype('int32')

In [54]:
c = np.array(([1,2,3],[4,5,6]))
print(c)

[[1 2 3]
 [4 5 6]]


In [55]:
c.dtype

dtype('int32')

In [56]:
a[1:2]

array([2])

In [65]:
a = np.arange(10,100,10)
a
#arange(from, end, interval)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
b = np.linspace(10,100,5)
b
#linspace(start, end, number of points in array)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [75]:
a = np.full((3,5),1)
a
#full((rows, columns), element)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [78]:
d = np.random.random((5,2))
d

array([[0.30068123, 0.53255279],
       [0.97537838, 0.66302895],
       [0.59644302, 0.07103909],
       [0.45612173, 0.37873447],
       [0.39001936, 0.74311755]])

In [79]:
d.shape

(5, 2)

In [81]:
# change the shape of the array
d.shape =(2,5)
d

array([[0.30068123, 0.53255279, 0.97537838, 0.66302895, 0.59644302],
       [0.07103909, 0.45612173, 0.37873447, 0.39001936, 0.74311755]])

In [83]:
d.ndim
#demensions

2

In [85]:
d.reshape(10,1)

array([[0.30068123],
       [0.53255279],
       [0.97537838],
       [0.66302895],
       [0.59644302],
       [0.07103909],
       [0.45612173],
       [0.37873447],
       [0.39001936],
       [0.74311755]])

In [86]:
d.reshape(1,10)

array([[0.30068123, 0.53255279, 0.97537838, 0.66302895, 0.59644302,
        0.07103909, 0.45612173, 0.37873447, 0.39001936, 0.74311755]])

In [96]:
np.sum([[1,2],[3,4]],axis=1)

array([3, 7])

In [97]:
d.mean()

0.5107116559437258

In [102]:
np.median(d)

0.4943372614164548

In [103]:
np.mean(d)

0.5107116559437258

In [104]:
np.max(d)

0.9753783795995469

In [105]:
np.min(d)

0.07103908986245833

In [106]:
np.sum(d)

5.107116559437258

In [107]:
np.std(d)

0.23944613925058145

In [112]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([3,4,5])
print(a)
print(b)
print(np.sum([a,b]))
# so numpy consider both array of the same size 
#and perform the operation on both th row. so it gives another array not one number.
#this is called array broadcasting

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[ 4  6  8]
 [ 7  9 11]]


In [110]:
np.subtract(a,b)

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [113]:
np.multiply(a,b)

array([[ 3,  8, 15],
       [12, 20, 30]])

In [116]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,5],[1,2,3]])
print(a)
print(b)
print(np.sum([a,b]))

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [1 2 3]]
39
